### ISSUE TITLE
Credential Provider Example

### ISSUE THREAD

**Issue by gkhanacer** [awsdocs/aws-cpp-developer-guide#6]
Is there any example like [this](http://docs.aws.amazon.com/cognito/latest/developerguide/getting-credentials.html). I want to use cognito with cpp, but I couldn't find any sample anywhere.

**Comment by EronHennessey** [comment]
I don't currently have a C++ example for Cognito yet (the existing examples are [here](https://github.com/awsdocs/aws-doc-sdk-examples/tree/master/cpp) -- even those without topics written for them).

However, since you've just requested one, I'll add it to my queue!

In the meanwhile, you can read more about the Amazon Cognito client for the C++ SDK here:

http://sdk.amazonaws.com/cpp/api/LATEST/class_aws_1_1_cognito_identity_1_1_cognito_identity_client.html

That, combined with the information in the [Amazon Cognito Developer Guide](http://docs.aws.amazon.com/cognito/latest/developerguide/getting-started.html) (for conceptual information and a few code examples in various languages) should get you started.

Thanks for the input!

**Comment by SCalwas** [comment]
Added writing a C++ Cognito example to my list of future examples.

Closing this feedback issue.
